# Generated by Django 3.2.9 on 2021-11-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('croncierge', '0002_task_crontab'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_periodic_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_periodic_task', to='django_celery_beat.periodictask'),
        ),
    ]
