# Generated by Django 3.2.9 on 2021-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croncierge', '0005_auto_20211127_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Set to False to disable the schedule', verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='task',
            name='one_off',
            field=models.BooleanField(default=False, help_text='If True, the schedule will only run the task a single time', verbose_name='One-off Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Datetime when the schedule should begin triggering the task to run', null=True, verbose_name='Start Datetime'),
        ),
    ]
